import { Link, useParams } from 'react-router-dom'
import { LockKeyhole } from 'lucide-react'
import { useWorkspace } from '../context/workspace'
import { Badge, Empty, Facts, Info, PageHeading, Panel, State } from '../components/Common'
import { BehaviourEvidence, EvidenceTree } from '../components/Evidence'
import Telemetry from '../components/Telemetry'
import { human } from '../utils/format'
export default function FindingDetails() {
  const { findingId } = useParams()
  const { risk, findings, refresh, entityName } = useWorkspace()
  const finding = findings.find(f => f.finding_id === findingId || f.source_finding_ids?.includes(findingId))
  return <><Link className="back-link" to="/findings">← Finding register</Link><State {...risk} retry={refresh}>{!finding ? <Empty title="Finding not found" description="This identifier is not in the current assessment. Refresh to retrieve the latest findings." /> : <>
    <PageHeading eyebrow={`${finding.rule_id} / ${human(finding.source_engine).toUpperCase()}`} title={human(finding.problem_type)} description={entityName(finding.entity_id)} action={<Badge value={finding.severity} />} />
    <div className="detail-grid"><div><Panel title="Finding rationale" subtitle="Generated by the existing analytics engine"><p className="lead-reason">{finding.reason}</p><Facts items={[["Assessment", <Badge value={finding.assessment} />], ["Organization", <Link to={`/entities/${finding.entity_id}`}>{entityName(finding.entity_id)}</Link>], ["Case", finding.case_id ? <Link to={`/cases/${finding.case_id}`}>{finding.case_id}</Link> : 'Asset-scoped finding'], ["Asset", finding.asset_id], ["Source engine", human(finding.source_engine)], ["Finding identifier", finding.finding_id]]} /></Panel>
      {finding.rule_id === 'R005' && finding.asset_id && <Telemetry finding={finding} />}
      <BehaviourEvidence finding={finding} />
      <Panel title="Structured source evidence" subtitle="Full evidence supplied by the backend; unknown values are preserved"><EvidenceTree value={finding.evidence} /><details className="disclosure"><summary>Source finding identifiers</summary><EvidenceTree value={finding.source_finding_ids} /></details></Panel>
    </div><aside><Panel title="Supervisor review" action={<LockKeyhole size={17} />}><div className="review-unavailable"><Badge value="unknown">Persistence unavailable</Badge><p>The backend does not yet store reviewer identity, decisions or comments.</p><fieldset disabled><legend>Review actions</legend><button className="button">Mark under review</button><button className="button">Confirm finding</button><button className="button">Dismiss finding</button><label>Reviewer comment<textarea placeholder="Comments require backend persistence" rows={4} /></label><button className="button primary">Save review</button></fieldset><Info>No reviewer action is saved locally or represented as a completed decision.</Info></div></Panel><Link className="text-link" to="/audit">Review capability and audit trail →</Link></aside></div>
  </>}</State></>
}
