import { Link, useSearchParams } from 'react-router-dom'
import { useWorkspace } from '../context/workspace'
import { Badge, Empty, Facts, Filter, Info, PageHeading, Panel, State } from '../components/Common'
import { Components } from '../components/Charts'
import { FindingTable, PriorityTable } from '../components/Tables'
import Benchmark from '../components/Benchmark'
import { number } from '../utils/format'
export default function Reports() {
  const { risk, reports, refresh } = useWorkspace()
  const [params, setParams] = useSearchParams()
  const selected = params.get('entity') || reports[0]?.entity_id || ''
  const report = reports.find(r => r.entity_id === selected)
  return <><PageHeading title="Supervisory reports" description="Current organization assessment and supporting evidence." /><State {...risk} retry={refresh}><div className="toolbar stand-alone"><Filter label="Report organization" value={selected} onChange={v => setParams(v ? { entity: v } : {})} options={reports.map(r => ({ value: r.entity_id, label: r.entity_name }))} all="Choose an organization" /><span className="muted">Live preview · PDF export is not available</span></div>{report ? <article className="report-preview"><div className="report-cover"><span className="eyebrow">SHADOWWATCH / SUPERVISORY ASSESSMENT</span><h2>{report.entity_name}</h2><p>{report.entity_id} · {report.sector} · {report.peer_group || 'No peer group'}</p><div className="report-score">{number(report.overall_score, 2)}<small>/ 100</small><Badge value={report.overall_level} /></div><p>{report.summary.explanation}</p><small>Data fetched: {risk.fetchedAt?.toLocaleString()} · {report.score_status}</small></div><div className="report-body"><Panel title="Risk components"><Components components={report.components} /></Panel><Panel title="Supervisory indicators"><Facts items={[["Execution gaps", report.aggregation.execution_gap_count], ["Negative-space findings", report.aggregation.negative_space_count], ["Behaviour indicators", report.aggregation.behaviour_analytics_count], ["Record contradictions", report.aggregation.contradiction_count], ["Monitored assets", report.denominators.monitored_assets], ["Monitored assets with telemetry", report.data_coverage.monitored_assets_with_telemetry]]} /></Panel><Panel title="Top contributors">{report.summary.top_contributors.length ? report.summary.top_contributors.map(c => <div className="report-contributor" key={c.rule_id}><strong>{c.rule_id} · {c.affected_cases} cases / {c.affected_assets} assets</strong><p>{c.example_reason}</p></div>) : <p className="inset">No scored contributors returned.</p>}</Panel><Panel title="Evidence for leading contributors"><FindingTable findings={report.summary.top_contributors.flatMap(c => report.findings.filter(f => f.finding_id === c.finding_ids[0]))} compact /></Panel><Panel title="Priority cases"><PriorityTable cases={report.summary.priority_cases} compact /></Panel><Benchmark report={report} /><Panel title="Coverage and limitations"><ul className="limitations">{report.limitations.map((text, i) => <li key={i}>{text}</li>)}</ul></Panel><Info>{report.disclaimer}</Info><Link className="button" to={`/entities/${report.entity_id}`}>Open organization workspace →</Link></div></article> : <Empty title="Select an organization to preview its report" />}</State></>
}
