import { BrowserRouter, Link, Navigate, Route, Routes } from 'react-router-dom'
import WorkspaceProvider from './context/WorkspaceProvider'
import ErrorBoundary from './components/ErrorBoundary'
import Layout from './components/Layout'
import { Empty } from './components/Common'
import Overview from './pages/Overview'
import Entities from './pages/Entities'
import EntityDetails from './pages/EntityDetails'
import Findings from './pages/Findings'
import FindingDetails from './pages/FindingDetails'
import PriorityCases from './pages/PriorityCases'
import CaseDetails from './pages/CaseDetails'
import WorkflowPage from './pages/WorkflowPage'
import Benchmarking from './pages/Benchmarking'
import Reports from './pages/Reports'
import Audit from './pages/Audit'
import System from './pages/System'
import './App.css'
export default function App() {
  return <ErrorBoundary><BrowserRouter><WorkspaceProvider><Routes><Route element={<Layout />}><Route index element={<Overview />} /><Route path="overview" element={<Navigate to="/" replace />} /><Route path="entities" element={<Entities />} /><Route path="entities/:entityId" element={<EntityDetails />} /><Route path="findings" element={<Findings />} /><Route path="findings/:findingId" element={<FindingDetails />} /><Route path="priority-cases" element={<PriorityCases />} /><Route path="cases/:caseId" element={<CaseDetails />} /><Route path="workflow" element={<WorkflowPage />} /><Route path="benchmarking" element={<Benchmarking />} /><Route path="reports" element={<Reports />} /><Route path="audit" element={<Audit />} /><Route path="system" element={<System />} /><Route path="*" element={<><Empty title="Page not found" description="This route is not part of the supervisor workspace." /><Link className="button" to="/">Return to overview</Link></>} /></Route></Routes></WorkspaceProvider></BrowserRouter></ErrorBoundary>
}
